CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;

CREATE TABLE public.classification (
    classification_id INTEGER GENERATED BY DEFAULT AS IDENTITY, -- Added INTEGER
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER varying NOT NULL,
    inv_model CHARACTER varying NOT NULL,
    inv_year CHARACTER VARYING(4) NOT NULL, -- Fixed: Moved (4) to the end
    inv_description TEXT NOT NULL,
    inv_image CHARACTER varying NOT NULL,
    inv_thumbnail CHARACTER varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color CHARACTER varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification
    FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) 
    MATCH SIMPLE ON UPDATE CASCADE
    ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
('Sports'),
('SUV'),
('Truck'),
('Sedan');